### PR TITLE
alter package file paths to keep nimble from complaining

### PR DESCRIPTION
**Pull request by platypython**

### CODE REVIEW

**Comment by dom96** [comment]
It might be better to just install the binary and none of the source files.

**Comment by dom96** [comment]
Unless it is @Araq's intention for c2nim's source files to be used as a library as well?

**Comment by platypython** [comment]
Honestly I don't know. I'm very new to nim, this being my first
contribution, and just kept making changes to the file locations until
nimble stopped complaining about where extra files were. Ran the tests, and
everything came  out OK.



On July 2, 2017 at 5:54:07 AM, Dominik Picheta (notifications@github.com)
wrote:

Unless it is @Araq <https://github.com/araq>'s intention for c2nim's source
files to be used as a library as well?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nim-lang/c2nim/pull/92#issuecomment-312487368>, or mute
the thread

**Comment by Araq** [comment]
c2nim is not a library, it's an application and can use the current directly layout. If nimble disagrees, we shall fix nimble.

**Pull request closed without merging**
