### PR TITLE
Add a parameter prefix for generated procs

### PR DESCRIPTION
**Pull request by data-man**
Also numbering of parameters is corrected.

### CODE REVIEW

**Comment by data-man** [comment]
The redness of the tests is not related to this PR.

**Comment by dom96** [comment]
I've locked the ``compiler`` dependency to ensure it works for the latest stable Nim release and devel.

You should be using ``nimble`` now to compile c2nim: ``nimble build`` inside the c2nim directory (or ``nimble c file.nim`` if you want to compile other files).

**Comment by data-man** [comment]
Tests are green.

**Comment by data-man** [comment]
The gentle ping.

**Pull request merged**
